# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    app.uldatabase:
        class: AppBundle\Util\ULDatabase
        arguments: ["@doctrine_mongodb.odm.default_connection", "@doctrine_mongodb"]
    app.ultaskrunner:
        class: AppBundle\Util\ULTaskRunner
        arguments: ["@app.uldatabase"]
    mongo.connection:
        class: Doctrine\MongoDB\Connection
        factory: ["@doctrine.odm.mongodb.document_manager", getConnection]
        calls:
            - [initialize, []]
    mongo:
        class: Mongo
        factory: ["@mongo.connection", getMongo]
